#!/usr/bin/env python
#
# midget-execution-device: a programmable QuickSilver clone
# Copyright (C) 2011 Thomas Lee

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

import os

settings.fifo = os.path.join(os.getenv("HOME"), ".medfifo")
settings.show_at_startup = False

commands.add("chrome", invoke, "chromium-browser", "${' '.join(args)}")
commands.add("google", invoke, "chromium-browser", "http://google.com/#q=${u(' '.join(args))}")
commands.add("terminal", invoke, "gnome-terminal", "--working-directory=${args[0]}")
commands.add("exit", quit)

